server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rodrigolrech/microsservices-config-server
          search-paths:
            - 'greeting-service*'

